### ISSUE TITLE
Create module for Seurat conversions

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenScPCA-analysis#945]
### Please link to the GitHub Discussion for this proposed analysis.

N/A

### Describe the goals of this analysis module.

As many users may want to use Seurat objects for their analysis, it would be convenient to have a central source of converted objects. This module will serve both as a source for those converted objects and as example code for use of the `rOpenScPCA::sce_to_seurat()` function.

### What software will you require?

The primary code will be in R with the `rOpenScPCA` and `Seurat` packages.

### What will your first pull request contain?

I will break the PR into the standard initialization PR followed by a code PR with the conversion scripts.

### What computational resources will you require?

All analysis should be possible on a laptop with minimal resources (only requiring memory to hold one SCE object)

### If known, when do you expect to file the first pull request?

By 12/17

**Comment by jashapiro** [comment]
Do I name this module `hello-seurat` or something a bit more descriptive like `seurat-conversion`?

**Comment by sjspielman** [comment]
> Do I name this module hello-seurat or something a bit more descriptive like seurat-conversion?

- I like `hello-` as an indicator for example/demonstration modules in general, but it does feel a bit odd for this one, even though I enjoy it. I don't think you can go wrong with either, since both are very clickable for different reasons!
- _But_, to the extent we want to implement other Seurat-related functionality, `hello-seurat` does allow for increased flexibility to present items other than conversion. I can't immediately think of what this might be, though.
